### ISSUE TITLE
specify target object to PAssert.IsTrue

### ISSUE THREAD

**Issue by wonderful-panda** [PowerAssert/PowerAssert.Net#25]
It would be nice if PAssert.IsTrue can accept target object.

```cs
var target = DoSomething();
PAssert.IsTrue(target, t => ...);

// Another syntax by extension method.
DoSomething().PAssert(t => ...);
```

**Comment by robfe** [comment]
I don't know about this one: Comparing

    var target = DoSomething();
    PAssert.IsTrue(target, t => ...);

And

    var target = DoSomething();
    PAssert.IsTrue(() => target...);

, what do you prefer about the former?

**Comment by wonderful-panda** [comment]
To be precise, what I want is this extention method.

```
DoSomething().PAssert(t => ...);
```

I think this syntax may make tests more fuss-free.

**Comment by robfe** [comment]
https://github.com/PowerAssert/PowerAssert.Net/blob/master/PowerAssert/PAssert.cs#L93 is essentially all you'd to make that work. Try it in an extension method in your own test project for a bit, and let me know if you do end up loving it.

**Comment by wonderful-panda** [comment]
I've try it.

Doing what PAssert.Substitute does will make output unreadable when target is complex type.
```cs
Expression<Func<bool>> Substitute<T>(T target, Expression<Func<T, bool>> expression)
{
  var c = Expression.Constant(target, typeof(T));
  var v = new ReplacementVisitor(expression.Parameters[0], c);
  var body = v.Visit(expression.Body);
  return Expression.Lambda<Func<bool>>(body);
}
```

For example, this assertion will show below output
```cs
var target = new [] {0, 1, 2, 3, 4};
target.PAssert(t => t[0] + t[1] + t[2] == 5);
```

```
[0, 1, 2, 3, 4, ... (10 total)][0] + [0, 1, 2, 3, 4, ... (10 total)][1] + [0, 1, 2, 3, 4, ... (10 total)][2] == 5
                               .   .                                .   .                                .   __
  ```

By another way as below, output become more readable.
```cs
Expression<Func<bool>> Substitute<T>(T target, Expression<Func<T, bool>> expression)
{
  Expression<Func<T>> e = () => target;
  var v = new ReplacementVisitor(expression.Parameters[0], e.Body);
  var body = v.Visit(expression.Body);
  return Expression.Lambda<Func<bool>>(body);
}
```

```
target[0] + target[1] + target[2] == 5
.    ..   . .    ..   . .    ..   __
```
This is almost perfect.
Only one tiny problem is that parameter name is replaced with 'target'.

If I can implement this inside of ExpressionParser, output will be exactly what I want.
https://github.com/wonderful-panda/PowerAssert.Net/commit/ed3de14980e5a06ba94b26fd2e11c96b49957376

```
t[0] + t[1] + t[2] + target == 5
..   . ..   . ..   . .    . __
```

**Comment by robfe** [comment]
ok, go for it :)

**Comment by wonderful-panda** [comment]
Thank you. I'll send Pull request later.
